name: "Heroku Container Deploy & Release"
description: "Push a container to Heroku and deploy."
branding:
  icon: "arrow-right"
  color: "purple"
inputs:
  heroku_email:
    description: "Heroku email address."
    required: true
  heroku_command:
    description: "Heroku application name."
    required: true
outputs:
  status:
    description: "The success / failure of the action."
runs:
  using: "node12"
  main: "index.js"
