name: "Heroku Container Deploy"
description: "Publish an container to Heroku app"
branding:
  icon: "arrow-right"
  color: "purple"
inputs:
  heroku_api_key:
    description: "This will be used for authentication. You can find it in your heroku homepage account settings"
    required: true
  heroku_email:
    description: "Email that you use with heroku"
    required: true
  heroku_command:
    description: "The appname being promoted"
    required: true
outputs:
  status:
    description: "The Success/Failure of the action"
runs:
  using: "node12"
  main: "index.js"
